### ISSUE TITLE
Changing language in settings.json crashes the launch

### ISSUE THREAD

**Issue by paradoxx42** [rfvgyhn/min-ed-launcher#127]
When changing the language setting from "null" to "en", the program crashes upon launch. Leaving the setting at "null" doesn't induce a crash though my game is not as I like it.
{
    "apiUri": "https://api.zaonce.net",
    "watchForCrashes": false,
    "language": en
    "autoUpdate": true,
    "checkForLauncherUpdates": true,
    "maxConcurrentDownloads": 4,
    "forceUpdate": "",
    "processes": [],
    "shutdownProcesses": [],
    "filterOverrides": [
        { "sku": "FORC-FDEV-DO-1000", "filter": "edo" },
        { "sku": "FORC-FDEV-DO-38-IN-40", "filter": "edh4" }
    ],
    "additionalProducts": []
}

**Debug log: terminal output**

[13:31:50 INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
[13:31:50 ERR] Unhandled exception: System.IO.InvalidDataException: Error_FailedToLoad, C:\Users\josua\AppData\Local\min-ed-launcher\settings.json
 ---> System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, e LineNumber: 3 | BytePositionInLine: 16.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1, JsonReaderOptions, MetadataDb&, StackRowStack&)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1, JsonReaderOptions, Byte[] , PooledByteBufferWriter )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
   at System.Text.Json.JsonDocument.Parse(String , JsonDocumentOptions )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String)
   at MinEdLauncher.Program.getSettings$cont@17(Assembly, String[], FSharpResult`2, Unit)
   at MinEdLauncher.Program.getSettings(Assembly, String[])
   at MinEdLauncher.Program.main(String[])
Press any key to quit...

**Debug log: min-ed-launcher.log**

2024-05-10 12:45:26.441 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 12:45:26.514 +02:00 [DBG] 
    Args: [||]
    OS: Win64
    Env: 
    
2024-05-10 12:45:26.515 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 12:45:26.603 +02:00 [ERR] Failed to find Elite Dangerous install directory
2024-05-10 12:55:03.913 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 12:55:03.987 +02:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=113...16f[32]"; "-AUTH_TYPE=exchangecode";
  "-epicapp=9c2...593[32]"; "-epicenv=Prod"; "-EpicPortal";
  "-epicusername=paradoxx_42"; "-epicuserid=35d...c45[32]";
  "-epiclocale=en"; "-epicsandboxid=3db...ac1[32]"|]
    OS: Win64
    Env: 
    
2024-05-10 12:55:03.990 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 12:55:04.112 +02:00 [DBG] Settings: { Platform = Epic { ExchangeCode = "113...16f[32]"
                    Type = "exchangecode"
                    AppId = "9c2...593[32]" }
  DisplayMode = Pancake
  AutoRun = false
  AutoQuit = false
  WatchForCrashes = false
  ProductWhitelist = seq []
  ForceLocal = true
  CompatTool = None
  CbLauncherDir = "D:\EpicGames\EliteDangerous\"
  PreferredLanguage = None
  ApiUri = https://api.zaonce.net/
  Restart = None
  AutoUpdate = true
  CheckForLauncherUpdates = true
  MaxConcurrentDownloads = 4
  ForceUpdate = set []
  Processes = []
  ShutdownProcesses = []
  FilterOverrides =
   seq [[FORC-FDEV-DO-1000, edo]; [FORC-FDEV-DO-38-IN-40, edh4]]
  AdditionalProducts = []
  DryRun = false
  ShutdownTimeout = 00:00:10
  CacheDir = "C:\Users\josua\AppData\Local\min-ed-launcher\cache"
  GameStartDelay = 00:00:00
  ShutdownDelay = 00:00:00 }
2024-05-10 12:55:04.119 +02:00 [INF] Elite Runtime
    Platform: Epic
    CobraBay Version: 1.7.6972.1
    Products Dir: D:\EpicGames\EliteDangerous\Products
2024-05-10 12:55:04.127 +02:00 [DBG] Getting machine id
2024-05-10 12:55:04.136 +02:00 [INF] Logging in
2024-05-10 12:55:04.136 +02:00 [DBG] Getting remote time
2024-05-10 12:55:04.458 +02:00 [DBG] Requesting epic token 
  Method: POST
  Uri: https://api.epicgames.dev/epic/oauth/v1/token
  Content: [
    grant_type=exchange_code
    exchange_code=113...16f[32]
    deployment_id=73d...6f3[32]
    scope=basic_profile friends_list presence
  ]
  Headers: {
    Authorization: Basic eHl...2NA[102]==
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
  }

2024-05-10 12:55:04.939 +02:00 [DBG] Requesting epic token success
2024-05-10 12:55:04.946 +02:00 [DBG] Authenticating via Epic
2024-05-10 12:55:05.690 +02:00 [DBG] Successfully authenticated
2024-05-10 12:55:05.691 +02:00 [INF] Logged in via Epic as: Josua Schmidt
2024-05-10 12:55:05.691 +02:00 [DBG] Getting authorized products
2024-05-10 12:55:05.836 +02:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Legacy Elite Dangerous","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_ed.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":false,"product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_arena.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Arena_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":true,"product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_ed.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":true,"product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Legacy Horizons","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_edh.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Horizons_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":false,"product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher/elite-dangerous-horizons-38/en.html"},{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"SeasonTwo","sortkey":"04","product_name":"Elite Dangerous: Horizons","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_edh.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Horizons_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Rebrand_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api.orerve.net","game_branch":40,"patch_notes_game_code":943,"no_details":false,"product_sku":"FORC-FDEV-DO-38-IN-40","template":"http://hosting.zaonce.net/launcher/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_art_edo_rebrand.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Odyssey_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Rebrand_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"16"},"game_api":"https://api.orerve.net","game_branch":40,"patch_notes_game_code":943,"no_details":false,"product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher/odyssey/en.html"}]}
2024-05-10 12:55:05.843 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Legacy Horizons,Legacy Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2024-05-10 12:55:05.843 +02:00 [INF] Checking for updates
2024-05-10 12:55:06.581 +02:00 [DBG] Launcher is latest release 0.10.1
2024-05-10 12:55:06.585 +02:00 [DBG] Unable to find product's version info at 'D:\EpicGames\EliteDangerous\Products\COMBAT_TUTORIAL_DEMO\VersionInfo.txt'
2024-05-10 12:55:07.429 +02:00 [INF] Available Products:
	Elite Dangerous: Odyssey      FORC-FDEV-DO-1000     Up to Date
	Elite Dangerous: Horizons     FORC-FDEV-DO-38-IN-40 Up to Date
	Legacy Horizons               FORC-FDEV-D-1013      Up to Date
	Legacy Elite Dangerous        FORC-FDEV-D-1010      Up to Date
	Elite Dangerous: Arena        FORC-FDEV-D-1012      Up to Date
	Single Player Combat Training COMBAT_TUTORIAL_DEMO  Not Installed
2024-05-10 12:55:11.030 +02:00 [DBG] User selected Elite Dangerous: Odyssey - FORC-FDEV-DO-1000 - edo
2024-05-10 12:55:11.293 +02:00 [INF] Launching Elite Dangerous: Odyssey
2024-05-10 12:55:11.301 +02:00 [DBG] Process: D:\EpicGames\EliteDangerous\Products\elite-dangerous-odyssey-64\EliteDangerous64.exe "ServerToken bd7...f9d[114] 0d3...66f[1774] " /language German\\DE "EpicToken eyJ...5lg[1067]" /novr
2024-05-10 13:09:05.595 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
2024-05-10 13:09:05.596 +02:00 [WRN] Unable to re-launch game without fully restarting the launcher when using an Epic account
2024-05-10 13:12:18.516 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 13:12:18.590 +02:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=5a1...6f4[32]"; "-AUTH_TYPE=exchangecode";
  "-epicapp=9c2...593[32]"; "-epicenv=Prod"; "-EpicPortal";
  "/autorun"; "/autoquit"; "/edo"; "-epicusername=paradoxx_42";
  "-epicuserid=35d...c45[32]"; "-epiclocale=en";
  "-epicsandboxid=3db...ac1[32]"|]
    OS: Win64
    Env: 
    
2024-05-10 13:12:18.594 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 13:12:18.631 +02:00 [ERR] Unhandled exception: System.IO.InvalidDataException: Error_FailedToLoad, C:\Users\josua\AppData\Local\min-ed-launcher\settings.json
 ---> System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, e LineNumber: 3 | BytePositionInLine: 16.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1, JsonReaderOptions, MetadataDb&, StackRowStack&)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1, JsonReaderOptions, Byte[] , PooledByteBufferWriter )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
   at System.Text.Json.JsonDocument.Parse(String , JsonDocumentOptions )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String)
   at MinEdLauncher.Program.getSettings$cont@17(Assembly, String[], FSharpResult`2, Unit)
   at MinEdLauncher.Program.getSettings(Assembly, String[])
   at MinEdLauncher.Program.main(String[])
2024-05-10 13:12:43.764 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 13:12:43.842 +02:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=a96...b13[32]"; "-AUTH_TYPE=exchangecode";
  "-epicapp=9c2...593[32]"; "-epicenv=Prod"; "-EpicPortal";
  "/autorun"; "/autoquit"; "/edo"; "-epicusername=paradoxx_42";
  "-epicuserid=35d...c45[32]"; "-epiclocale=en";
  "-epicsandboxid=3db...ac1[32]"|]
    OS: Win64
    Env: 
    
2024-05-10 13:12:43.846 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 13:12:43.884 +02:00 [ERR] Unhandled exception: System.IO.InvalidDataException: Error_FailedToLoad, C:\Users\josua\AppData\Local\min-ed-launcher\settings.json
 ---> System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, e LineNumber: 3 | BytePositionInLine: 16.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1, JsonReaderOptions, MetadataDb&, StackRowStack&)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1, JsonReaderOptions, Byte[] , PooledByteBufferWriter )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
   at System.Text.Json.JsonDocument.Parse(String , JsonDocumentOptions )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String)
   at MinEdLauncher.Program.getSettings$cont@17(Assembly, String[], FSharpResult`2, Unit)
   at MinEdLauncher.Program.getSettings(Assembly, String[])
   at MinEdLauncher.Program.main(String[])
2024-05-10 13:12:59.155 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 13:12:59.232 +02:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=0fe...807[32]"; "-AUTH_TYPE=exchangecode";
  "-epicapp=9c2...593[32]"; "-epicenv=Prod"; "-EpicPortal";
  "/autorun"; "/autoquit"; "/edo"; "-epicusername=paradoxx_42";
  "-epicuserid=35d...c45[32]"; "-epiclocale=en";
  "-epicsandboxid=3db...ac1[32]"|]
    OS: Win64
    Env: 
    
2024-05-10 13:12:59.236 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 13:12:59.361 +02:00 [DBG] Settings: { Platform = Epic { ExchangeCode = "0fe...807[32]"
                    Type = "exchangecode"
                    AppId = "9c2...593[32]" }
  DisplayMode = Pancake
  AutoRun = true
  AutoQuit = true
  WatchForCrashes = false
  ProductWhitelist = seq ["edo"]
  ForceLocal = true
  CompatTool = None
  CbLauncherDir = "D:\EpicGames\EliteDangerous\"
  PreferredLanguage = None
  ApiUri = https://api.zaonce.net/
  Restart = None
  AutoUpdate = true
  CheckForLauncherUpdates = true
  MaxConcurrentDownloads = 4
  ForceUpdate = set []
  Processes = []
  ShutdownProcesses = []
  FilterOverrides =
   seq [[FORC-FDEV-DO-1000, edo]; [FORC-FDEV-DO-38-IN-40, edh4]]
  AdditionalProducts = []
  DryRun = false
  ShutdownTimeout = 00:00:10
  CacheDir = "C:\Users\josua\AppData\Local\min-ed-launcher\cache"
  GameStartDelay = 00:00:00
  ShutdownDelay = 00:00:00 }
2024-05-10 13:12:59.369 +02:00 [INF] Elite Runtime
    Platform: Epic
    CobraBay Version: 1.7.6972.1
    Products Dir: D:\EpicGames\EliteDangerous\Products
2024-05-10 13:12:59.376 +02:00 [DBG] Getting machine id
2024-05-10 13:12:59.385 +02:00 [INF] Logging in
2024-05-10 13:12:59.386 +02:00 [DBG] Getting remote time
2024-05-10 13:12:59.692 +02:00 [DBG] Requesting epic token 
  Method: POST
  Uri: https://api.epicgames.dev/epic/oauth/v1/token
  Content: [
    grant_type=exchange_code
    exchange_code=0fe...807[32]
    deployment_id=73d...6f3[32]
    scope=basic_profile friends_list presence
  ]
  Headers: {
    Authorization: Basic eHl...2NA[102]==
    Content-Type: application/x-www-form-urlencoded; charset=utf-8
  }

2024-05-10 13:13:00.178 +02:00 [DBG] Requesting epic token success
2024-05-10 13:13:00.185 +02:00 [DBG] Authenticating via Epic
2024-05-10 13:13:00.539 +02:00 [DBG] Successfully authenticated
2024-05-10 13:13:00.540 +02:00 [INF] Logged in via Epic as: Josua Schmidt
2024-05-10 13:13:00.540 +02:00 [DBG] Getting authorized products
2024-05-10 13:13:00.681 +02:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Legacy Elite Dangerous","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_ed.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":false,"product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_arena.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Arena_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":true,"product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_ed.jpg","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":true,"product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Legacy Horizons","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_edh.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Horizons_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Refresh_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api3x.orerve.net","game_branch":38,"patch_notes_game_code":13,"no_details":false,"product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher/elite-dangerous-horizons-38/en.html"},{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"SeasonTwo","sortkey":"04","product_name":"Elite Dangerous: Horizons","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_edh.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Horizons_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Rebrand_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"7"},"game_api":"https://api.orerve.net","game_branch":40,"patch_notes_game_code":943,"no_details":false,"product_sku":"FORC-FDEV-DO-38-IN-40","template":"http://hosting.zaonce.net/launcher/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","imageset":{"box":"http://hosting.zaonce.net/launcher_new/images/box_art_edo_rebrand.png","hero":"http://hosting.zaonce.net/launcher_new/images/Elite_Dangerous_Odyssey_LauncherHero.png","logo":"http://hosting.zaonce.net/launcher_new/logos/ED_Rebrand_Logo_Full_White.png"},"ratings":{"esrb":"teen","pegi":"16"},"game_api":"https://api.orerve.net","game_branch":40,"patch_notes_game_code":943,"no_details":false,"product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher/odyssey/en.html"}]}
2024-05-10 13:13:00.689 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Legacy Horizons,Legacy Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2024-05-10 13:13:00.689 +02:00 [INF] Checking for updates
2024-05-10 13:13:01.101 +02:00 [DBG] Launcher is latest release 0.10.1
2024-05-10 13:13:01.104 +02:00 [DBG] Unable to find product's version info at 'D:\EpicGames\EliteDangerous\Products\COMBAT_TUTORIAL_DEMO\VersionInfo.txt'
2024-05-10 13:13:01.943 +02:00 [INF] Available Products:
	Elite Dangerous: Odyssey      FORC-FDEV-DO-1000     Up to Date
	Elite Dangerous: Horizons     FORC-FDEV-DO-38-IN-40 Up to Date
	Legacy Horizons               FORC-FDEV-D-1013      Up to Date
	Legacy Elite Dangerous        FORC-FDEV-D-1010      Up to Date
	Elite Dangerous: Arena        FORC-FDEV-D-1012      Up to Date
	Single Player Combat Training COMBAT_TUTORIAL_DEMO  Not Installed
2024-05-10 13:13:02.108 +02:00 [INF] Launching Elite Dangerous: Odyssey
2024-05-10 13:13:02.115 +02:00 [DBG] Process: D:\EpicGames\EliteDangerous\Products\elite-dangerous-odyssey-64\EliteDangerous64.exe "ServerToken fcc...53e[114] fae...ff5[1772] " /language German\\DE "EpicToken eyJ...jmA[1067]" /novr
2024-05-10 13:13:29.959 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
2024-05-10 13:31:50.735 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.10.1+ab8b6bfb
2024-05-10 13:31:50.812 +02:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=230...fcd[32]"; "-AUTH_TYPE=exchangecode";
  "-epicapp=9c2...593[32]"; "-epicenv=Prod"; "-EpicPortal";
  "/autorun"; "/autoquit"; "/edo"; "-epicusername=paradoxx_42";
  "-epicuserid=35d...c45[32]"; "-epiclocale=en";
  "-epicsandboxid=3db...ac1[32]"|]
    OS: Win64
    Env: 
    
2024-05-10 13:31:50.816 +02:00 [DBG] Reading settings from 'C:\Users\josua\AppData\Local\min-ed-launcher\settings.json'
2024-05-10 13:31:50.855 +02:00 [ERR] Unhandled exception: System.IO.InvalidDataException: Error_FailedToLoad, C:\Users\josua\AppData\Local\min-ed-launcher\settings.json
 ---> System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, e LineNumber: 3 | BytePositionInLine: 16.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&, ExceptionResource, Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1, JsonReaderOptions, MetadataDb&, StackRowStack&)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1, JsonReaderOptions, Byte[] , PooledByteBufferWriter )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
   at System.Text.Json.JsonDocument.Parse(String , JsonDocumentOptions )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String)
   at MinEdLauncher.Program.getSettings$cont@17(Assembly, String[], FSharpResult`2, Unit)
   at MinEdLauncher.Program.getSettings(Assembly, String[])
   at MinEdLauncher.Program.main(String[])

**Comment by rfvgyhn** [comment]
The language is a string value and should be wrapped in quotes.

`"language": "en"` instead of `"language": en`.

**Comment by paradoxx42** [comment]
Ah, that makes sense. It worked, thanks!
