### ISSUE TITLE
Fails to launch on proton + beta Steam client

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Rfvgyhn/min-ed-launcher#26]
```
2021-05-26 06:56:09.899 +02:00 [DBG] User selected Elite Dangerous: Odyssey - FORC-FDEV-DO-1000 - edh
2021-05-26 06:56:10.031 +02:00 [INF] Launching Elite Dangerous: Odyssey
2021-05-26 06:56:10.110 +02:00 [DBG] Process: /games/steam/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe "ServerToken xxx " /language English\\UK /steam /novr
2021-05-26 06:56:10.138 +02:00 [ERR] Couldn't start selected product: System.ComponentModel.Win32Exception (8): Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MinEdLauncher.Product.run(FSharpOption`1 proton, String args, RunnableProduct product)
```

Using proton experimental. Game launches fine via the vanilla launcher.

**Comment by Rfvgyhn** [comment]
It looks like it didn't recognize proton at all and it's trying to run the elite exe directly. I'm unable to reproduce on my end. Can you post the full log for that run? Does this only happen with the experimental version other versions of proton as well?

**Comment by pan-mroku** [comment]
I think I have the same problem (the game doesn't launch after an array of updates a few days ago. It was working before)  and your diagnosis is right.

Log from some time ago:

```
2021-05-21 00:21:03.087 +02:00 [DBG] Args: [|"/home/pawel/newhome/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/EDO"|]
2021-05-21 00:21:03.222 +02:00 [DBG] Reading settings from '/home/pawel/.config/min-ed-launcher/settings.json'
2021-05-21 00:21:03.673 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = true
    AutoQuit = true
    WatchForCrashes = false
    ProductWhitelist = set []
    ForceLocal = true
    Proton =
            Some
              { EntryPoint =
                            "/home/pawel/newhome/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
                Args =
                      [|"--verb=waitforexitandrun"; "--"; "python3";
                        "/home/pawel/newhome/SteamLibrary/steamapps/common/Proton - Experimental/proton";
                        "waitforexitandrun"|] }
    CbLauncherDir =
                   "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = (false, 3000L)
    Processes = [] }
2021-05-21 00:21:03.677 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2021-05-21 00:21:03.755 +02:00 [INF] Elite Dangerous - Minimal Launcher
Platform: Steam
OS: Linux64
CobraBay Version: 0.4.6705.0
Launcher Version: 0.3.1
Products Dir: /home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products
2021-05-21 00:21:04.686 +02:00 [DBG] Got steam client
2021-05-21 00:21:04.686 +02:00 [DBG] Got steam pipe
2021-05-21 00:21:04.688 +02:00 [DBG] Got steam global user
2021-05-21 00:21:04.689 +02:00 [DBG] Got steam user
2021-05-21 00:21:04.690 +02:00 [DBG] Requesting steam auth ticket
2021-05-21 00:21:04.690 +02:00 [DBG] Got steam auth ticket
2021-05-21 00:21:04.695 +02:00 [DBG] Authenticating via Steam
2021-05-21 00:21:05.084 +02:00 [DBG] Successfully authenticated
2021-05-21 00:21:05.084 +02:00 [DBG] Disposing Steam resources
2021-05-21 00:21:05.085 +02:00 [DBG] Cancelling auth ticket
2021-05-21 00:21:05.085 +02:00 [DBG] closing steam
2021-05-21 00:21:05.092 +02:00 [INF] Logged in via Steam as: Paweł Szymański
2021-05-21 00:21:05.092 +02:00 [DBG] Getting authorized products
2021-05-21 00:21:06.676 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2021-05-21 00:21:06.676 +02:00 [INF] Checking for updates
2021-05-21 00:21:08.329 +02:00 [INF] Available Products:
        (Elite Dangerous: Odyssey, Up to date)
        (Elite Dangerous: Horizons, Up to date)
        (Elite Dangerous, Up to date)
        (Elite Dangerous: Arena, Up to date)
        (Single Player Combat Training, Up to date)
2021-05-21 00:21:08.491 +02:00 [INF] Launching Elite Dangerous: Odyssey
2021-05-21 00:21:08.619 +02:00 [DBG] Process: /home/pawel/newhome/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point "--verb=waitforexitandrun" "--" "python3" "/home/pawel/newhome/SteamLibrary/steamapps/common/Proton - Experimental/proton" "waitforexitandrun" "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe" "ServerToken 90b...c39ad9...722f7e...c0909a8797d42cb2cce203986e47f0e 5cd...8cfdee...a11574...b5aa88...e1fbb4...647080...12a348...99f535...129684...17a02f...146858...aca6fa...858d46...35ccbc...a23c21...15e5fb...ad27a7...f27425...73a713...115152...790516...9bb9cb...1c1f69...f5f191...1f25d7...addfee...3b23f5...9fc86f...cb60e0...4f95ba...f7b93b...1f73fe...291051...58fc30...3d404a...15f2cb...712433...97537029352b94edc8149 " /language English\\UK /steam /novr
2021-05-21 03:47:57.520 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
```

As you can see I was playing the game for a few hours here. Logs now using proton-experimental and 6.3-4

```
2021-05-26 23:19:45.637 +02:00 [DBG] Args: [|"/home/pawel/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper";
  "SteamLaunch"; "AppId=359320"; "--";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/EDO"|]
2021-05-26 23:19:45.780 +02:00 [DBG] Reading settings from '/home/pawel/.config/min-ed-launcher/settings.json'
2021-05-26 23:19:46.259 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = true
    AutoQuit = false
    WatchForCrashes = false
    ProductWhitelist = set ["edo"]
    ForceLocal = true
    Proton = None
    CbLauncherDir =
                   "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = (false, 3000L)
    AutoUpdate = true
    MaxConcurrentDownloads = 4
    ForceUpdate = set []
    Processes = [] }
2021-05-26 23:19:46.262 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2021-05-26 23:19:46.337 +02:00 [INF] Elite Dangerous - Minimal Launcher
Platform: Steam
OS: Linux64
CobraBay Version: 0.4.6709.0
Launcher Version: 0.4.0
Products Dir: /home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products
2021-05-26 23:19:47.260 +02:00 [DBG] Got steam client
2021-05-26 23:19:47.261 +02:00 [DBG] Got steam pipe
2021-05-26 23:19:47.263 +02:00 [DBG] Got steam global user
2021-05-26 23:19:47.264 +02:00 [DBG] Got steam user
2021-05-26 23:19:47.264 +02:00 [DBG] Requesting steam auth ticket
2021-05-26 23:19:47.264 +02:00 [DBG] Got steam auth ticket
2021-05-26 23:19:47.269 +02:00 [DBG] Authenticating via Steam
2021-05-26 23:19:47.562 +02:00 [DBG] Successfully authenticated
2021-05-26 23:19:47.563 +02:00 [DBG] Disposing Steam resources
2021-05-26 23:19:47.563 +02:00 [DBG] Cancelling auth ticket
2021-05-26 23:19:47.563 +02:00 [DBG] closing steam
2021-05-26 23:19:47.570 +02:00 [INF] Logged in via Steam as: Paweł Szymański
2021-05-26 23:19:47.571 +02:00 [DBG] Getting authorized products
2021-05-26 23:19:49.143 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2021-05-26 23:19:49.143 +02:00 [INF] Checking for updates
2021-05-26 23:19:50.731 +02:00 [INF] Available Products:
        Elite Dangerous: Odyssey      FORC-FDEV-DO-1000    Up to Date
        Elite Dangerous: Horizons     FORC-FDEV-D-1013     Up to Date
        Elite Dangerous               FORC-FDEV-D-1010     Up to Date
        Elite Dangerous: Arena        FORC-FDEV-D-1012     Up to Date
        Single Player Combat Training COMBAT_TUTORIAL_DEMO Up to Date
2021-05-26 23:19:50.913 +02:00 [INF] Launching Elite Dangerous: Odyssey
2021-05-26 23:19:51.036 +02:00 [DBG] Process: /home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe "ServerToken 5d0...6450f9...96abd4...9521fcadf67375b625a85a29e566383 1cd...9e1141...884496...b4cb9a...35862e...545a45...c392eb...654f0a...d6df74...4444a0...d48111...1e1448...8f4706...e76910...fa8ef5...b71342...95173d...9c89c2...1a4337...ab4b9d...024341...e679b2...3b3fd6...e6eba9...642876...369189...3ee71a...95619f...afdcc5...57c6c1...02e19c...9d41ef...420e01...2f9bd7...a7f434...205544...7c2ea9...29bbc4e161c4a8be41ef3 " /language English\\UK /steam /novr
2021-05-26 23:19:53.680 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
```

```
2021-05-26 23:20:57.623 +02:00 [DBG] Args: [|"/home/pawel/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper"; "SteamLaunch"; "AppId=359320"; "--";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Proton 6.3/proton";
  "waitforexitandrun";
  "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/EDO"|]
2021-05-26 23:20:57.771 +02:00 [DBG] Reading settings from '/home/pawel/.config/min-ed-launcher/settings.json'
2021-05-26 23:20:58.254 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = true
    AutoQuit = true
    WatchForCrashes = false
    ProductWhitelist = set ["edo"]
    ForceLocal = true
    Proton = None
    CbLauncherDir =
                   "/home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = (false, 3000L)
    AutoUpdate = true
    MaxConcurrentDownloads = 4
    ForceUpdate = set []
    Processes = [] }
2021-05-26 23:20:58.257 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2021-05-26 23:20:58.332 +02:00 [INF] Elite Dangerous - Minimal Launcher
Platform: Steam
OS: Linux64
CobraBay Version: 0.4.6709.0
Launcher Version: 0.4.0
Products Dir: /home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products
2021-05-26 23:20:59.249 +02:00 [DBG] Got steam client
2021-05-26 23:20:59.249 +02:00 [DBG] Got steam pipe
2021-05-26 23:20:59.252 +02:00 [DBG] Got steam global user
2021-05-26 23:20:59.252 +02:00 [DBG] Got steam user
2021-05-26 23:20:59.253 +02:00 [DBG] Requesting steam auth ticket
2021-05-26 23:20:59.253 +02:00 [DBG] Got steam auth ticket
2021-05-26 23:20:59.258 +02:00 [DBG] Authenticating via Steam
2021-05-26 23:20:59.575 +02:00 [DBG] Successfully authenticated
2021-05-26 23:20:59.576 +02:00 [DBG] Disposing Steam resources
2021-05-26 23:20:59.576 +02:00 [DBG] Cancelling auth ticket
2021-05-26 23:20:59.576 +02:00 [DBG] closing steam
2021-05-26 23:20:59.583 +02:00 [INF] Logged in via Steam as: Paweł Szymański
2021-05-26 23:20:59.583 +02:00 [DBG] Getting authorized products
2021-05-26 23:21:00.934 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2021-05-26 23:21:00.934 +02:00 [INF] Checking for updates
2021-05-26 23:21:02.714 +02:00 [INF] Available Products:
        Elite Dangerous: Odyssey      FORC-FDEV-DO-1000    Up to Date
        Elite Dangerous: Horizons     FORC-FDEV-D-1013     Up to Date
        Elite Dangerous               FORC-FDEV-D-1010     Up to Date
        Elite Dangerous: Arena        FORC-FDEV-D-1012     Up to Date
        Single Player Combat Training COMBAT_TUTORIAL_DEMO Up to Date
2021-05-26 23:21:02.892 +02:00 [INF] Launching Elite Dangerous: Odyssey
2021-05-26 23:21:03.015 +02:00 [DBG] Process: /home/pawel/newhome/SteamLibrary/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe "ServerToken d36...4bde9d...e73aad...32ff0f984fd904a68f89fe23d9b0f7e 004...be14ac...52a037...e208f7...38e09e...0c99ca...d15785...98679d...ccd9e2...e1f8e3...c1db8e...47cd72...816266...0c037c...832b64...7f7df8...1acd71...972056...d432fe...ecc052...ba4a3c...bfb616...07805e...024bd7...1009e3...32fd67...a9e280...96d1b5...4b30cd...12cbad...111234...022ef9...0d6b9b...8303d3...0c4c1e...5669ed...931214...cdb9f687f6bb3a1e53d39 " /language English\\UK /steam /novr
2021-05-26 23:21:06.131 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
```

Before upgrade to 0.4.0 it was also not working.

**Comment by Rfvgyhn** [comment]
`reaper` is something I haven't seen before. I opted into the steam client beta and now see the same problem as @pan-mroku. I don't get an exception though so I'm not certain these are the same problems.

@A-UNDERSCORE-D Does your log also have `$HOME/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper` as the first arg?

**Comment by pan-mroku** [comment]
Yes, after opting out of steam beta I no longer have the problem. I hope I did not hijack the issue.

**Comment by A-UNDERSCORE-D** [comment]
Correct `2021-05-26 06:56:02.973 +02:00 [DBG] Args: [|"/home/ad/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper"; "SteamLaunch";`

Also running the steam beta

**Comment by Rfvgyhn** [comment]
That explains it. The launcher determines if proton is needed by the first argument that's passed in. I'd never seen the usage of `reaper` before so it doesn't account for that. You'll need to use the non-beta version until I can add support for `reaper`.

**Comment by A-UNDERSCORE-D** [comment]
Sounds good! what even is reaper?

**Comment by Rfvgyhn** [comment]
My guess would be that it cleans up zombie processes (which I've noticed isn't uncommon with proton's use of pressure-vessel). That's typically referred to as reaping.

**Comment by pan-mroku** [comment]
FWIW the only sensible mention of that program I've found is [this](https://github.com/ValveSoftware/steam-runtime/issues/321#issuecomment-743169445).

**Comment by bekopharm** [comment]
Afraid this is no longer in beta but was rolled out. I'm not on the beta and sadly MinEdLauncher stopped working for me too. There is a process sitting idle when then autoquit option is removed:

> beko       32569  1.4  0.2 3571420 87348 pts/2   Ssl+ 10:33   0:01 ./MinEdLauncher /home/beko/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper SteamLaunch AppId=359320 -- /drive_d/games/
steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /games/steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /games/steam/steamapps/com
mon/Elite Dangerous/EDLaunch.exe /Steam /novr /autorun /EDO

![image](https://user-images.githubusercontent.com/5016428/121321623-8f8c6500-c90e-11eb-97e0-44e6e93744aa.png)

Steam Info is

![image](https://user-images.githubusercontent.com/5016428/121321814-b8acf580-c90e-11eb-9bcc-b69fd1c26abf.png)

**Comment by Rfvgyhn** [comment]
I've been unable to get it to run with `reaper` and proton >= 5.13. I have a temp workaround implemented at the moment that just ignores `reaper` completely. [v0.5.2](https://github.com/Rfvgyhn/min-ed-launcher/releases/tag/v0.5.2) should allow the game to launch now, but work still needs to be done to get it to run with `reaper`.
