### ISSUE TITLE
" ERR] No selected project" when using /autostart /edo

### ISSUE THREAD

**Issue by NaturalHate** [Rfvgyhn/min-ed-launcher#33]
```
2021-06-19 23:28:27.110 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.5.3
2021-06-19 23:28:27.248 +02:00 [DBG] 
    Args: [|"/home/*****/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper";
  "SteamLaunch"; "AppId=359320"; "--";
  "/home/*****/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/*****/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/home/*****/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/edo"|]
    OS: Linux64
    
2021-06-19 23:28:27.260 +02:00 [DBG] Reading settings from '/home/*****/.config/min-ed-launcher/settings.json'
2021-06-19 23:28:27.540 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = true
    AutoQuit = true
    WatchForCrashes = false
    ProductWhitelist = seq ["edo"]
    ForceLocal = true
    Proton =
            Some
              { EntryPoint =
                            "/home/*****/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
                Args =
                      [|"--verb=waitforexitandrun"; "--"; "python3";
                        "/home/*****/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
                        "waitforexitandrun"|] }
    CbLauncherDir =
                   "/home/*****/.local/share/Steam/steamapps/common/Elite Dangerous"
    PreferredLanguage = None
    ApiUri = https://api.zaonce.net/
    Restart = None
    AutoUpdate = true
    MaxConcurrentDownloads = 4
    ForceUpdate = set ["FORC-FDEV-DO-1000"]
    Processes = []
    FilterOverrides = seq [] }
2021-06-19 23:28:27.542 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2021-06-19 23:28:27.583 +02:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6709.0
    Products Dir: /home/*****/.local/share/Steam/steamapps/common/Elite Dangerous/Products
2021-06-19 23:28:28.165 +02:00 [DBG] Got steam client
2021-06-19 23:28:28.165 +02:00 [DBG] Got steam pipe
2021-06-19 23:28:28.168 +02:00 [DBG] Got steam global user
2021-06-19 23:28:28.168 +02:00 [DBG] Got steam user
2021-06-19 23:28:28.169 +02:00 [DBG] Requesting steam auth ticket
2021-06-19 23:28:28.169 +02:00 [DBG] Got steam auth ticket
2021-06-19 23:28:28.171 +02:00 [DBG] Authenticating via Steam
2021-06-19 23:28:28.821 +02:00 [DBG] Successfully authenticated
2021-06-19 23:28:28.822 +02:00 [DBG] Disposing Steam resources
2021-06-19 23:28:28.822 +02:00 [DBG] Cancelling auth ticket
2021-06-19 23:28:28.822 +02:00 [DBG] closing steam
2021-06-19 23:28:28.826 +02:00 [INF] Logged in via Steam as: *****
2021-06-19 23:28:28.826 +02:00 [DBG] Getting authorized products
2021-06-19 23:28:30.554 +02:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Elite Dangerous","product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Elite Dangerous: Horizons","product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher-steam/odyssey/en.html"}]}
2021-06-19 23:28:30.583 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2021-06-19 23:28:30.583 +02:00 [INF] Checking for updates
2021-06-19 23:28:30.589 +02:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at '/home/*****/.local/share/Steam/steamapps/common/Elite Dangerous/Products/COMBAT_TUTORIAL_DEMO/VersionInfo.txt'
2021-06-19 23:28:32.509 +02:00 [INF] Available Products:
	Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
	Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
	Elite Dangerous           FORC-FDEV-D-1010  Up to Date
	Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
2021-06-19 23:28:32.526 +02:00 [ERR] No selected project


```

Manual start without arguments works fine.

**Comment by Rfvgyhn** [comment]
Did you happen to upgrade from a previous version without updating your filter overrides? If so, you'll need to add the following to your `settings.json` file to workaround an FDev [bug](https://issues.frontierstore.net/issue-detail/33154).

```json
"filterOverrides": [
    { "sku": "FORC-FDEV-DO-1000", "filter": "edo" }
  ]
```

**Comment by NaturalHate** [comment]
I guess? I had I think 4.4.0, which threw a longer error after updating the game, which caused me to see if an updated version of the launcher is available, since I did not want to report something potentially caused by an old version. Just replaced the old one with the new version, like I would do with any other software update too. I wasn't aware I needed to manually edit the config file.
Adding that to the config throws me this error though.

`
2021-06-20 13:39:56.056 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.5.3
2021-06-20 13:39:56.195 +02:00 [DBG] 
    Args: [|"/home/*****/.local/share/Steam/ubuntu12_32/../ubuntu12_32/reaper";
  "SteamLaunch"; "AppId=359320"; "--";
  "/home/*****/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/*****/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/home/*****/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/edo"|]
    OS: Linux64
    
2021-06-20 13:39:56.207 +02:00 [DBG] Reading settings from '/home/*****/.config/min-ed-launcher/settings.json'
2021-06-20 13:39:56.265 +02:00 [ERR] Unhandled exception: System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: FoundInvalidCharacter, " LineNumber: 4 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Con...CommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String fileName)
   at MinEdLauncher.Program.getSettings(String[] args)
   at MinEdLauncher.Program.main@51-3.Invoke(Unit _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
`

**Comment by Rfvgyhn** [comment]
Looks like a missing or extra character is in your settings file. You can try pasting the contents of your settings file in a linter like https://jsonlint.com/, comparing to the [sample](https://github.com/Rfvgyhn/min-ed-launcher#settings) json in the readme or just deleting the file and let it be regenerated (just remember any changes you've made so you can reapply them).

Also, if you're curious about what's been updated, you can check out the [changelog](https://github.com/Rfvgyhn/min-ed-launcher/blob/master/CHANGELOG.md).

**Comment by NaturalHate** [comment]
Looks like you need to add a "," after ""processes": []" if you want to add the lines you've mentioned.
