### ISSUE TITLE
after update 6 for oddesy

### ISSUE THREAD

**Issue by thedevouttrout** [Rfvgyhn/min-ed-launcher#35]
2021-07-30 01:41:27.714 -04:00 [DBG] Reading settings from 'C:\Users\My Luna\AppData\Local\min-ed-launcher\settings.json'
2021-07-30 01:41:28.092 -04:00 [DBG] Settings: Ok { Platform = Steam
     DisplayMode = Pancake
     AutoRun = true
     AutoQuit = true
     WatchForCrashes = true
     ProductWhitelist = seq []
     ForceLocal = true
     Proton = None
     CbLauncherDir = "F:\SteamLibrary\steamapps\common\Elite Dangerous"
     PreferredLanguage = None
     ApiUri = https://api.zaonce.net/
     Restart = None
     AutoUpdate = true
     MaxConcurrentDownloads = 4
     ForceUpdate = set []
     Processes = []
     FilterOverrides = seq [[FORC-FDEV-DO-1000, edo]] }
2021-07-30 01:41:28.103 -04:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6709.0
    Products Dir: F:\SteamLibrary\steamapps\common\Elite Dangerous\Products
2021-07-30 01:41:29.034 -04:00 [DBG] Got steam client
2021-07-30 01:41:29.034 -04:00 [DBG] Got steam pipe
2021-07-30 01:41:29.035 -04:00 [DBG] Got steam global user
2021-07-30 01:41:29.035 -04:00 [DBG] Got steam user
2021-07-30 01:41:29.036 -04:00 [DBG] Requesting steam auth ticket
2021-07-30 01:41:29.036 -04:00 [DBG] Got steam auth ticket
2021-07-30 01:41:29.039 -04:00 [DBG] Authenticating via Steam
2021-07-30 01:41:29.787 -04:00 [DBG] Successfully authenticated
2021-07-30 01:41:29.788 -04:00 [DBG] Disposing Steam resources
2021-07-30 01:41:29.788 -04:00 [DBG] Cancelling auth ticket
2021-07-30 01:41:29.788 -04:00 [DBG] closing steam
2021-07-30 01:41:29.793 -04:00 [INF] Logged in via Steam as: cody werdal
2021-07-30 01:41:29.794 -04:00 [DBG] Getting authorized products
2021-07-30 01:41:31.594 -04:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"}]}
2021-07-30 01:41:31.611 -04:00 [DBG] Authorized Products: Single Player Combat Training
2021-07-30 01:41:31.611 -04:00 [INF] Checking for updates
2021-07-30 01:41:31.613 -04:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at 'F:\SteamLibrary\steamapps\common\Elite Dangerous\Products\COMBAT_TUTORIAL_DEMO\VersionInfo.txt'
2021-07-30 01:41:31.673 -04:00 [ERR] Unhandled exception: System.AggregateException: AggregateException_ctor_DefaultMessage (The input sequence was empty. Arg_ParamName_Name, list)
 ---> System.ArgumentException: The input sequence was empty. Arg_ParamName_Name, list
   at MinEdLauncher.App.max@346(FSharpList`1 _arg10, FSharpFunc`2 f)
   at MinEdLauncher.App.continuation@1-59(LauncherSettings settings, CancellationToken cancellationToken, HttpClient _arg1, DateTime localTime, Int64 _arg3, String machineId, Connection connection, FSharpList`1 _arg10)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at MinEdLauncher.App.continuation@328-55.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.combine@240.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.App.run@291-7.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.Program.main@59-8.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   Exception_EndOfInnerExceptionStack
   
   
   
   
   
   this is my latest log entry, not sure what is going on, fresh install windows 10 64bit

**Comment by Rfvgyhn** [comment]
It looks like FDev's server responded with you only owning the combat tutorial demo (Purchases Response). Since it's not installed, the launcher found no products to start.

Does the normal launcher work? If so, you might try again. It could have just been a server issue on their end.

**Comment by thedevouttrout** [comment]
the normal launcher is stuck in an update required bug, i own all of the main dlc as well as the game itself, so that must be a serverside issue
