### ISSUE TITLE
It do not work after 2021/9/23 update.

### ISSUE THREAD

**Issue by kiplring** [Rfvgyhn/min-ed-launcher#36]
Epic Store. It worked until 2021/9/22.

2021-09-24 20:24:33.146 +09:00 [DBG] Reading settings from 'C:\Users\username\AppData\Local\min-ed-launcher\settings.json'
2021-09-24 20:24:33.333 +09:00 [DBG] Settings: Error "Unknown platform. Failed to find Elite Dangerous install directory"
2021-09-24 20:24:33.333 +09:00 [ERR] Unknown platform. Failed to find Elite Dangerous install directory

**Comment by Rfvgyhn** [comment]
I'm unable to reproduce this issue. Can you post the full output in the log file?

**Comment by kiplring** [comment]
> I'm unable to reproduce this issue. Can you post the full output in the log file?

log msg changed. this is a full log.

2021-09-25 22:54:07.086 +09:00 [INF] Elite Dangerous: Minimal Launcher - v0.5.3
2021-09-25 22:54:07.168 +09:00 [DBG] 
    Args: [|"/Epic"; "-AUTH_LOGIN=unused";
  "-AUTH_PASSWORD=asdfasdfasdf"; "-AUTH_TYPE=exchangecode";
  "-epicapp=asdfasdfasdf"; "-epicenv=Prod"; "-EpicPortal";
  "/autorun"; "/autoquit"; "/EDO"; "/novr"; "-epicusername=asdfasdfasdf";
  "-epicuserid=asdfasdfasdf"; "-epiclocale=en";
  "-epicsandboxid=asdfasdfasdf"|]
    OS: Win64
    
2021-09-25 22:54:07.186 +09:00 [DBG] Reading settings from 'C:\Users\asdfasdfasdf\AppData\Local\min-ed-launcher\settings.json'
2021-09-25 22:54:07.231 +09:00 [ERR] Unhandled exception: System.FormatException: Error_JSONParseError
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, e LineNumber: 3 | BytePositionInLine: 16.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   Exception_EndOfInnerExceptionStack
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MinEdLauncher.Settings.parseConfig(String fileName)
   at MinEdLauncher.Program.getSettings(String[] args)
   at MinEdLauncher.Program.main@51-3.Invoke(Unit _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

**Comment by Rfvgyhn** [comment]
That error message means there's a syntax error in your `settings.json` file. You can try debugging it yourself with something like https://jsonlint.com/ or you can post the contents of your settings file here and I can take a look.

**Comment by kiplring** [comment]
I restored backup file of "C:\Users\username\AppData\Local\min-ed-launcher\settings.json".
And it works fine.
Thanks!
