### ISSUE TITLE
Crashes after update without logs

### ISSUE THREAD

**Issue by Romdeau4** [rfvgyhn/min-ed-launcher#52]
I am trying to get MinEdLauncher to work on my Ubuntu 22.04 Budgie instance, but the launcher closes as soon as it gets to checking for updates.

I have checked for crash logs, but there are no files there:

```
$: ~/.config/min-ed-launcher$ stat $XDG_STATE_HOME/min-ed-launcher/min-ed-launcher.log
stat: cannot statx '/min-ed-launcher/min-ed-launcher.log': No such file or directory

$: ~/.config/min-ed-launcher$ stat ~/.local/state
stat: cannot statx '/home/sbdavis/.local/state': No such file or directory
```

I have tried with both experimental proton, 6.3, and 7

It does look like the `settings.json` file is getting created though:

```
$: ~/.config/min-ed-launcher$ find ./
./
./settings.json
```

System specs:
```
$ neofetch
           ./oydmMMMMMMmdyo/.              sbdavis@caliburn-ubuntu 
        :smMMMMMMMMMMMhs+:++yhs:           ----------------------- 
     `omMMMMMMMMMMMN+`        `odo`        OS: Ubuntu Budgie 22.04.1 LTS x86_64 
    /NMMMMMMMMMMMMN-            `sN/       Host: MS-7D42 1.0 
  `hMMMMmhhmMMMMMMh               sMh`     Kernel: 5.15.0-46-generic 
 .mMmo-     /yMMMMm`              `MMm.    Uptime: 10 hours, 55 mins 
 mN/       yMMMMMMMd-              MMMm    Packages: 1949 (dpkg), 17 (snap) 
oN-        oMMMMMMMMMms+//+o+:    :MMMMo   Shell: bash 5.1.16 
m/          +NMMMMMMMMMMMMMMMMm. :NMMMMm   Resolution: 1920x1080, 1920x1080 
M`           .NMMMMMMMMMMMMMMMNodMMMMMMM   DE: Budgie 10.6.1 
M-            sMMMMMMMMMMMMMMMMMMMMMMMMM   WM: Mutter(Budgie) 
mm`           mMMMMMMMMMNdhhdNMMMMMMMMMm   Theme: Pocillo-dark [GTK2/3] 
oMm/        .dMMMMMMMMh:      :dMMMMMMMo   Icons: Pocillo [GTK2/3] 
 mMMNyo/:/sdMMMMMMMMM+          sMMMMMm    Terminal: tilix 
 .mMMMMMMMMMMMMMMMMMs           `NMMMm.    CPU: 12th Gen Intel i7-12700F (20) @ 
  `hMMMMMMMMMMM.oo+.            `MMMh`     GPU: AMD ATI Radeon RX 6800/6800 XT  
    /NMMMMMMMMMo                sMN/       Memory: 4659MiB / 31961MiB 
     `omMMMMMMMMy.            :dmo`
        :smMMMMMMMh+-`   `.:ohs:                                   
           ./oydmMMMMMMdhyo/.                                      
```

For what it's worth, I haven't been able to get ED to launch using Linux Mint either. If I don't use the MinEdLauncher and just use proton, the launcher starts but throws a message saying the launcher is out of date and I have no choice but to close it out.

**Comment by rfvgyhn** [comment]
The current readme includes updates that haven't been released yet including the log file location change. You should have a log file in the `logs` folder that's in the same location as the binary.

**Comment by Romdeau4** [comment]
It looks like it's authenticating into Steam, but when it gets a list of purchased products it can't find any so I only get the combat demo. I don't have the combat demo in my directory, so it crashes. In the "Products" folder, I only have `elite-dangerous-64`. I bought the game through Steam back in like 2016 and linked my Steam account to my new Frontier account.

![Screenshot from 2022-08-15 22-22-21](https://user-images.githubusercontent.com/14046805/184784864-4d53a47e-4487-4c7e-be9b-6f60f0761505.png)


```
2022-08-15 18:14:43.377 -04:00 [DBG] Got steam client
2022-08-15 18:14:43.377 -04:00 [DBG] Got steam pipe
2022-08-15 18:14:43.380 -04:00 [DBG] Got steam global user
2022-08-15 18:14:43.381 -04:00 [DBG] Got steam user
2022-08-15 18:14:43.382 -04:00 [DBG] Requesting steam auth ticket
2022-08-15 18:14:43.382 -04:00 [DBG] Got steam auth ticket
2022-08-15 18:14:43.386 -04:00 [DBG] Authenticating via Steam
2022-08-15 18:14:44.232 -04:00 [DBG] Successfully authenticated
2022-08-15 18:14:44.233 -04:00 [DBG] Disposing Steam resources
2022-08-15 18:14:44.233 -04:00 [DBG] Cancelling auth ticket
2022-08-15 18:14:44.233 -04:00 [DBG] closing steam
2022-08-15 18:14:44.238 -04:00 [INF] Logged in via Steam as: ###REDACTED###
2022-08-15 18:14:44.238 -04:00 [DBG] Getting authorized products
2022-08-15 18:14:46.140 -04:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"}]}
2022-08-15 18:14:46.149 -04:00 [DBG] Authorized Products: Single Player Combat Training
2022-08-15 18:14:46.149 -04:00 [INF] Checking for updates
2022-08-15 18:14:46.151 -04:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at '/home/sbdavis/.steam/debian-installation/steamapps/common/Elite Dangerous/Products/COMBAT_TUTORIAL_DEMO/VersionInfo.txt'
2022-08-15 18:14:46.183 -04:00 [ERR] Unhandled exception: System.AggregateException: AggregateException_ctor_DefaultMessage (Argument_InvalidResourceCultureName, en_us.utf-8)
 ---> System.ArgumentException: Argument_InvalidResourceCultureName, en_us.utf-8
   at System.Globalization.CultureInfo.VerifyCultureName(String cultureName, Boolean throwException)
   at System.Resources.ResourceManager.GetResourceFileName(CultureInfo culture)
   at System.Resources.ResourceManager.ResourceManagerMediator.GetResourceFileName(CultureInfo culture)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at MinEdLauncher.App.max@346(FSharpList`1 _arg10, FSharpFunc`2 f)
   at MinEdLauncher.App.continuation@1-59(LauncherSettings settings, CancellationToken cancellationToken, HttpClient _arg1, DateTime localTime, Int64 _arg3, String machineId, Connection connection, FSharpList`1 _arg10)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at MinEdLauncher.App.continuation@328-55.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.combine@240.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.App.run@291-7.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.Program.main@59-8.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   Exception_EndOfInnerExceptionStack
```

**Comment by rfvgyhn** [comment]
This looks like an account linking issue. FDev's API says you don't own the game.

When you say you linked it to your new frontier account, does that mean a different one than in the past? I'm not sure how frontier decides on game licenses, but it could be the case that you can't link to more than one account.

You could try [directly logging in with your frontier account](https://github.com/rfvgyhn/min-ed-launcher#frontier-account-via-steam-or-epic) since you have a pre-april 2019 purchase.

You might have to contact frontier support to get the issue resolved. If you do contact them, you might mention that the response to `https://api.zaonce.net/3.0/user/purchases` (purchases response) only returns the combat demo for your linked account.

**Comment by Romdeau4** [comment]
After opening a ticket with Frontier Support, they confirmed my CD key was actually registered to an older email of mine. I was able to log into that Frontier account, register it with Steam, and everything worked from there.

Thanks so much!
