### ISSUE TITLE
Unknown platform when using Terminator Terminal

### ISSUE THREAD

**Issue by arne-fuchs** [rfvgyhn/min-ed-launcher#53]
I get the following error if I try to start the launcher with following steam command:
`MANGOHUD=1 terminator -x bash -c './MinEdLauncher %command% > edlaunch.log'`
`[00:58:01 INF] Elite Dangerous: Minimal Launcher - v0.5.4
[00:58:01 ERR] Unknown platform. Failed to find Elite Dangerous install directory`

Sadly simply running 
`terminator -x ./MinEdLauncher %command%` 
didn't do the trick, because it just terminates.
Same with -e and trying to run it through bash.

Running Ubuntu 22.04.
It works with gnome-terminal.

**Comment by arne-fuchs** [comment]
`2022-08-17 23:53:07.804 +02:00 [DBG] 
    Args: [|"/home/arne/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
  "AppId=359320"; "--";
  "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/proton";
  "waitforexitandrun";
  "/home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"|]
    OS: Linux64
    
2022-08-17 23:53:07.815 +02:00 [DBG] Reading settings from '/home/arne/.config/min-ed-launcher/settings.json'
2022-08-17 23:53:08.089 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = false
    AutoQuit = false
    WatchForCrashes = false
    ProductWhitelist = seq []
    ForceLocal = true
    Proton =
            Some
              { EntryPoint =
                            "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
                Args =
                      [|"--verb=waitforexitandrun"; "--"; "python3";
                        "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/proton";
                        "waitforexitandrun"|] }
    CbLauncherDir =
                   "/home/arne/.local/share/Steam/steamapps/common/Elite Dangerous"
    PreferredLanguage = Some "de"
    ApiUri = https://api.zaonce.net/
    Restart = None
    AutoUpdate = true
    MaxConcurrentDownloads = 4
    ForceUpdate = set []
    Processes = []
    FilterOverrides = seq [[FORC-FDEV-DO-1000, edo]] }
2022-08-17 23:53:08.091 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2022-08-17 23:53:08.127 +02:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6725.0
    Products Dir: /home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/Products
2022-08-17 23:53:08.606 +02:00 [DBG] Got steam client
2022-08-17 23:53:08.606 +02:00 [DBG] Got steam pipe
2022-08-17 23:53:08.608 +02:00 [DBG] Got steam global user
2022-08-17 23:53:08.608 +02:00 [DBG] Got steam user
2022-08-17 23:53:08.609 +02:00 [DBG] Requesting steam auth ticket
2022-08-17 23:53:08.609 +02:00 [DBG] Got steam auth ticket
2022-08-17 23:53:08.612 +02:00 [DBG] Authenticating via Steam
2022-08-17 23:53:09.339 +02:00 [DBG] Successfully authenticated
2022-08-17 23:53:09.340 +02:00 [DBG] Disposing Steam resources
2022-08-17 23:53:09.340 +02:00 [DBG] Cancelling auth ticket
2022-08-17 23:53:09.340 +02:00 [DBG] closing steam
2022-08-17 23:53:09.344 +02:00 [INF] Logged in via Steam as: Arne Fuchs
2022-08-17 23:53:09.344 +02:00 [DBG] Getting authorized products
2022-08-17 23:53:11.141 +02:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Elite Dangerous","product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Elite Dangerous: Horizons","product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher-steam/odyssey/en.html"}]}
2022-08-17 23:53:11.155 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2022-08-17 23:53:11.155 +02:00 [INF] Checking for updates
2022-08-17 23:53:11.161 +02:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at '/home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/Products/COMBAT_TUTORIAL_DEMO/VersionInfo.txt'
2022-08-17 23:53:13.027 +02:00 [INF] Available Products:
	Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
	Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
	Elite Dangerous           FORC-FDEV-D-1010  Up to Date
	Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
2022-08-17 23:53:13.064 +02:00 [ERR] Unhandled exception: System.AggregateException: AggregateException_ctor_DefaultMessage (InvalidOperation_ConsoleReadKeyOnFile)
 ---> System.InvalidOperationException: InvalidOperation_ConsoleReadKeyOnFile
   at System.ConsolePal.ReadKey(Boolean intercept)
   at MinEdLauncher.App.readInput@123(ProductDetails[] products, CancellationToken cancellationToken, Unit unitVar0)
   at MinEdLauncher.App.promptForProductToPlay(ProductDetails[] products, CancellationToken cancellationToken)
   at MinEdLauncher.App.continuation@1-71(LauncherSettings settings, CancellationToken cancellationToken, DateTime localTime, Int64 _arg3, String machineId, Connection connection, FSharpList`1 _arg10, FSharpList`1 _arg16)
   at MinEdLauncher.App.continuation@399-66.Invoke(Unit unitVar)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at MinEdLauncher.App.continuation@340-60.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.combine@240.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.App.run@291-7.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.Program.main@59-8.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   Exception_EndOfInnerExceptionStack`

**Comment by arne-fuchs** [comment]
I dont know if this error is relevant, because I already had a problem before and fixed it by build the launcher myself.
Since then there are no new logs written in the logs folder.

**Comment by rfvgyhn** [comment]
Ah, didn't realize you were using the latest git version. In that case, the log files have moved to a standard location and would be in `$XDG_STATE_HOME/min-ed-launcher` (`~/.local/state` if `$XDG_STATE_HOME` isn't set).

**Comment by arne-fuchs** [comment]
2022-08-18 01:01:49.270 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.5.4
2022-08-18 01:01:49.427 +02:00 [DBG] 
    Args: [|"/home/arne/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
  "AppId=359320"; "--";
  "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/proton";
  "waitforexitandrun"; "/home/arne/.local/share/Steam/steamapps/common/Elite";
  "Dangerous/EDLaunch.exe"; "/Steam"; "/novr"|]
    OS: Linux64
    
2022-08-18 01:01:49.455 +02:00 [DBG] Reading settings from '/home/arne/.config/min-ed-launcher/settings.json'
2022-08-18 01:01:49.735 +02:00 [DBG] Settings: Ok
  { Platform = Steam
    DisplayMode = Pancake
    AutoRun = false
    AutoQuit = false
    WatchForCrashes = false
    ProductWhitelist = seq []
    ForceLocal = true
    CompatTool =
     Some
       { EntryPoint =
          "/home/arne/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point"
         Args =
          [|"--verb=waitforexitandrun"; "--"; "python3";
            "/home/arne/.local/share/Steam/compatibilitytools.d/GE-Proton7-29/proton";
            "waitforexitandrun";
            "/home/arne/.local/share/Steam/steamapps/common/Elite"|] }
    CbLauncherDir = "Dangerous"
    PreferredLanguage = Some "de"
    ApiUri = https://api.zaonce.net/
    Restart = None
    AutoUpdate = true
    MaxConcurrentDownloads = 4
    ForceUpdate = set []
    Processes = []
    FilterOverrides = seq [[FORC-FDEV-DO-1000, edo]] }
2022-08-18 01:01:49.770 +02:00 [ERR] Unhandled exception: System.AggregateException: AggregateException_ctor_DefaultMessage (IO_PathNotFound_Path, /home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/Dangerous)
 ---> System.IO.DirectoryNotFoundException: IO_PathNotFound_Path, /home/arne/.local/share/Steam/steamapps/common/Elite Dangerous/Dangerous
   at Interop.ThrowExceptionForIoErrno(ErrorInfo , String , Boolean , Func`2 )
   at Interop.CheckIo(Int64 , String , Boolean , Func`2 )
   at Interop.CheckIo(Int32 , String , Boolean , Func`2 )
   at System.Environment.set_CurrentDirectoryCore(String )
   at System.Environment.set_CurrentDirectory(String )
   at System.IO.Directory.SetCurrentDirectory(String )
   at MinEdLauncher.Program.main@65-5.Invoke(Unit unitVar)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   Exception_EndOfInnerExceptionStack

**Comment by arne-fuchs** [comment]
Seems like the IO Path is missing a "\" in the path which causes the program to get an extra Parameter?

**Comment by arne-fuchs** [comment]
Okay I am giving up on terminator. It can't get the environmental variables. I will change the emulator.
Sucks for the effort. 
Closing the issue.
