### ISSUE TITLE
Launcher did not find my game installation

### ISSUE THREAD

**Issue by DunkleAura** [rfvgyhn/min-ed-launcher#56]
Hi,

first thank you for the min-launcher. but i noticed a little issue.

```
2022-09-17 13:52:51.425 +02:00 [DBG] Disabling 'Elite Dangerous: Odyssey'. Unable to find product at 'C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products\elite-dangerous-odyssey-64\VersionInfo.txt'
2022-09-17 13:52:51.425 +02:00 [DBG] Disabling 'Elite Dangerous: Horizons'. Unable to find product at 'C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products\elite-dangerous-64\VersionInfo.txt'
2022-09-17 13:52:51.426 +02:00 [DBG] Disabling 'Elite Dangerous'. Unable to find product at 'C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products\elite-dangerous-64\VersionInfo.txt'
2022-09-17 13:52:51.426 +02:00 [DBG] Disabling 'Elite Dangerous: Arena'. Unable to find product at 'C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products\elite-dangerous-64\VersionInfo.txt'
2022-09-17 13:52:51.426 +02:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at 'C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products\COMBAT_TUTORIAL_DEMO\VersionInfo.txt'
2022-09-17 13:52:51.505 +02:00 [ERR] Unhandled exception: System.AggregateException: AggregateException_ctor_DefaultMessage (The input sequence was empty. Arg_ParamName_Name, list)
 ---> System.ArgumentException: The input sequence was empty. Arg_ParamName_Name, list
   at MinEdLauncher.App.max@346(FSharpList`1 products, FSharpFunc`2 f)
   at MinEdLauncher.App.continuation@1-57(LauncherSettings settings, CancellationToken cancellationToken, HttpClient httpClient, DateTime localTime, Int64 remoteTime, String machineId, Connection connection, FSharpList`1 products)
   at MinEdLauncher.App.continuation@328-74.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.combine@240.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.AwaitableContinuation`3.Invoke(Unit r)
   at Ply.TplPrimitives.tryFinally@257.Invoke(AwaitableContinuation`3 this)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.App.run@291-13.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at MinEdLauncher.Program.main@73-7.Invoke(Unit unitVar0)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   Exception_EndOfInnerExceptionStack
```

The problem is, my C:\ drive is pretty full so i used in the original launcher under options "Select Installation Directory" and did install Elite on "D:\Gaming\Frontier". This means in `C:\Users\USERNAME\AppData\Local\Frontier_Developments\Products` are 2 text files:
* elite-dangerous-64.rdr
* elite-dangerous-odyssey-64.rdr
Both have just one line in it `D:\Gaming\Frontier` which points to the actual installation.

It would be very cool if you could add support for this.

Thank you.

**Comment by rfvgyhn** [comment]
So in `D:\Gaming\Frontier`, you have two folders named `elite-dangerous-odyssey-64` and `elite-dangerous-64`, correct?
