### ISSUE TITLE
min-ed-launcher stopped working

### ISSUE THREAD

**Issue by zezic** [rfvgyhn/min-ed-launcher#60]
At some point min-ed-lanucher stopped working for me, I tried to update to the latest version (v0.7.0+2638963b), but it does not help. I can't figure out what has changed, original Frontier launcher continue to work. Here is the log:

```log
zezic@CH6H:~/.local/state/min-ed-launcher$ tail -f min-ed-launcher.log 
2022-09-24 19:12:29.123 +03:00 [INF] Elite Dangerous: Minimal Launcher - v0.7.0+2638963b
2022-09-24 19:12:29.260 +03:00 [DBG] 
    Args: [|"/home/zezic/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
  "AppId=359320"; "--";
  "/home/zezic/.local/share/Steam/ubuntu12_32/steam-launch-wrapper"; "--";
  "/home/TERA/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/zezic/.local/share/Steam/compatibilitytools.d/GE-Proton7-26/proton";
  "waitforexitandrun";
  "/home/TERA/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/autoquit"; "/EDO"|]
    OS: Linux64
    Env: STEAM_COMPAT_DATA_PATH=/home/TERA/SteamLibrary/steamapps/compatdata/359320
    
2022-09-24 19:12:29.264 +03:00 [DBG] Reading settings from '/home/zezic/.config/min-ed-launcher/settings.json'
2022-09-24 19:12:29.511 +03:00 [DBG] Settings: { Platform = Steam
  DisplayMode = Pancake
  AutoRun = true
  AutoQuit = true
  WatchForCrashes = false
  ProductWhitelist =
   seq
     ["edo";
      "home/tera/steamlibrary/steamapps/common/elite dangerous/edlaunch.exe";
      "home/tera/steamlibrary/steamapps/common/steamlinuxruntime_soldier/_v2-entry-point";
      "home/zezic/.local/share/steam/compatibilitytools.d/ge-proton7-26/proton";
      ...]
  ForceLocal = true
  CompatTool = None
  CbLauncherDir = "/home/TERA/SteamLibrary/steamapps/common/Elite Dangerous/"
  PreferredLanguage = None
  ApiUri = https://api.zaonce.net/
  Restart = None
  AutoUpdate = true
  MaxConcurrentDownloads = 4
  ForceUpdate = set []
  Processes = []
  FilterOverrides = seq [[FORC-FDEV-DO-1000, edo]]
  AdditionalProducts = [] }
2022-09-24 19:12:29.527 +03:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2022-09-24 19:12:29.560 +03:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6725.0
    Products Dir: /home/TERA/SteamLibrary/steamapps/common/Elite Dangerous/Products
2022-09-24 19:12:30.331 +03:00 [DBG] Got steam client
2022-09-24 19:12:30.331 +03:00 [DBG] Got steam pipe
2022-09-24 19:12:30.334 +03:00 [DBG] Got steam global user
2022-09-24 19:12:30.335 +03:00 [DBG] Got steam user
2022-09-24 19:12:30.336 +03:00 [DBG] Requesting steam auth ticket
2022-09-24 19:12:30.336 +03:00 [DBG] Got steam auth ticket
2022-09-24 19:12:30.340 +03:00 [DBG] Authenticating via Steam
2022-09-24 19:12:31.011 +03:00 [DBG] Successfully authenticated
2022-09-24 19:12:31.012 +03:00 [DBG] Disposing Steam resources
2022-09-24 19:12:31.012 +03:00 [DBG] Cancelling auth ticket
2022-09-24 19:12:31.012 +03:00 [DBG] closing steam
2022-09-24 19:12:31.014 +03:00 [INF] Logged in via Steam as: Sergey Ukolov
2022-09-24 19:12:31.014 +03:00 [DBG] Getting authorized products
2022-09-24 19:12:32.751 +03:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Elite Dangerous","product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Elite Dangerous: Horizons","product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher-steam/odyssey/en.html"}]}
2022-09-24 19:12:32.765 +03:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2022-09-24 19:12:32.766 +03:00 [INF] Checking for updates
2022-09-24 19:12:32.770 +03:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at '/home/TERA/SteamLibrary/steamapps/common/Elite Dangerous/Products/COMBAT_TUTORIAL_DEMO/VersionInfo.txt'
2022-09-24 19:12:34.665 +03:00 [INF] Available Products:
        Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
        Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
        Elite Dangerous           FORC-FDEV-D-1010  Up to Date
        Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
2022-09-24 19:12:34.750 +03:00 [INF] Launching Elite Dangerous: Odyssey
2022-09-24 19:12:34.883 +03:00 [DBG] Process: /home/TERA/SteamLibrary/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe "ServerToken ddc...471c93...22dd3b...27f3cf5 ca8...9e8cfe...76fa03...8bbb64...38d28d...15cf2c...d651c8...4e743e...79de1e...db69da...787371...d55d57...5b317b...be374f...7bd282...06d043...48cd39...95df07...6a20c1...65f424...02a1e4...81d0b1...e160e5...053453...7fc4db...02aa26...2a52e0...b7c600...9bb0a5...2918a5...361995...74efbc...be230a...bf88de...84ef13...246c76...afeea0...c94acc...518156...0300f9...4e0d5abefc9346494dcf4e397af " /language English\\UK /steam /novr
2022-09-24 19:12:34.927 +03:00 [INF] Shutdown Elite Dangerous: Odyssey
^C
```

**Comment by rfvgyhn** [comment]
It looks like the game shuts down immediately after starting. Does using a different version of proton change anything?

**Comment by nirui** [comment]
Well, since I'm there already... I got a different error message:

    ERROR: ld.so: object '/home/MYUSERNAME/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
    [10:30:17 INF] Elite Dangerous: Minimal Launcher - v0.7.0+2638963b
    [10:30:18 INF] Elite Runtime
        Platform: Steam
        CobraBay Version: 0.4.6725.0
        Products Dir: /home/MYUSERNAME/.local/share/Steam/steamapps/common/Elite Dangerous/Products
    [S_API] SteamAPI_Init(): Loaded '/home/MYUSERNAME/.local/share/Steam/linux64/steamclient.so' OK.
    Setting breakpad minidump AppID = 359320
    SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198012844270 [API loaded no]
    [10:30:20 INF] Logged in via Steam as: MYACCOUNTNAME
    [10:30:22 INF] Checking for updates
    [10:30:27 INF] Available Products:
        Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
        Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
        Elite Dangerous           FORC-FDEV-D-1010  Up to Date
        Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
    [10:30:27 INF] Launching Elite Dangerous: Odyssey
    [10:30:27 ERR] Couldn't start selected product: System.ComponentModel.Win32Exception (8): ErrorStartingProcess, /home/MYUSERNAME/.local/share/Steam/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe, /home/MYUSERNAME/.local/share/Steam/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64, Exec format error
    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo , String , String[] , String[] , String , Boolean , UInt32 , UInt32 , UInt32[] , Int32& , Int32& , Int32& , Boolean , Boolean )
    at System.Diagnostics.Process.StartCore(ProcessStartInfo )
    at System.Diagnostics.Process.Start()
    at System.Diagnostics.Process.Start(ProcessStartInfo )
    at MinEdLauncher.Product.run(FSharpOption`1 proton, String args, RunnableProduct product)
    Press any key to quit...

I was using the version 0.5. Few days ago the game stopped launching and MinEdLauncher produces similar error shown above. My launch setup hasn't changed during the time, so I assume something happened to the game(???)

Upgrading to 0.7 did not fix the problem (but it did provides a bit more info about the error, though). 

The official launcher works fine, but it's slow like hell as usual.

**Comment by HerrCraziDev** [comment]
Same issue. Been playing Odyssey on Arch Linux for months with no issues. Went thru updates without problems. And all of a sudden, when launched from `min-ed-launcher` (using command line `mangohud konsole -e ./MinEdLauncher %command% /autorun /autoquit /EDO`), the game opens in a smaller, windowed screen, and crashes. Occasionally, a Wine configuration popup shows, just like when you first startup Wine. This behavior is similar to manually launching the Odyssey executable with Wine. 

I played a week ago without issues. Launching via the default launcher works (but sucks).

**Comment by lwho** [comment]
Also stopped working for me after last Wednesday, but for me it's failing even earlier in the process:

```
2022-09-25 11:30:56.638 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.7.0+2638963b
2022-09-25 11:30:56.786 +02:00 [DBG] 
    Args: [|"/home/ubuntu/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
  "AppId=359320"; "--";
  "/home/ubuntu/.local/share/Steam/ubuntu12_32/steam-launch-wrapper"; "--";
  "/games/steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/ubuntu/.local/share/Steam/compatibilitytools.d/Proton-6.5-GE-2/proton";
  "waitforexitandrun";
  "/games/steam/steamapps/common/Elite Dangerous/EDLaunch.exe"; "/Steam";
  "/novr"; "/autorun"; "/autoquit"; "/EDH4"|]
    OS: Linux64
    Env: STEAM_COMPAT_DATA_PATH=/home/ubuntu/compatdata/359320
    
2022-09-25 11:30:56.788 +02:00 [DBG] Reading settings from '/home/ubuntu/.config/min-ed-launcher/settings.json'
2022-09-25 11:30:57.027 +02:00 [ERR] Failed to find Elite Dangerous install directory
```

I was using 0.5.3 up to now, but upgraded to 0.7.0 now. Same effect in both versions.

**Comment by HerrCraziDev** [comment]
Changing Proton versions did not help. Steam is up to date, the launcher and the system as well. Nothing strange. The game just crashes silently when ran with this launcher. No errors, nothing.
I'll attach the logs, but didn't find anything suspect in there.

```
2022-09-25 15:44:06.344 +02:00 [INF] Elite Dangerous: Minimal Launcher - v0.7.0+2638963b
2022-09-25 15:44:06.472 +02:00 [DBG] 
    Args: [|"/home/herrcrazi/.local/share/Steam/ubuntu12_32/reaper"; "SteamLaunch";
  "AppId=359320"; "--";
  "/home/herrcrazi/.local/share/Steam/ubuntu12_32/steam-launch-wrapper"; "--";
  "/home/herrcrazi/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point";
  "--verb=waitforexitandrun"; "--";
  "/home/herrcrazi/.local/share/Steam/steamapps/common/Proton - Experimental/proton";
  "waitforexitandrun";
  "/media/DATA/SteamLibrary/steamapps/common/Elite Dangerous/EDLaunch.exe";
  "/Steam"; "/novr"; "/autorun"; "/EDO"|]
    OS: Linux64
    Env: STEAM_COMPAT_DATA_PATH=/media/DATA/SteamLibrary/steamapps/compatdata/359320
    
2022-09-25 15:44:06.476 +02:00 [DBG] Reading settings from '/home/herrcrazi/.config/min-ed-launcher/settings.json'
2022-09-25 15:44:06.705 +02:00 [DBG] Settings: { Platform = Steam
  DisplayMode = Pancake
  AutoRun = true
  AutoQuit = false
  WatchForCrashes = false
  ProductWhitelist =
   seq
     ["edo";
      "home/herrcrazi/.local/share/steam/steamapps/common/proton - experimental/proton";
      "home/herrcrazi/.local/share/steam/steamapps/common/steamlinuxruntime_soldier/_v2-entry-point";
      "home/herrcrazi/.local/share/steam/ubuntu12_32/steam-launch-wrapper"; ...]
  ForceLocal = true
  CompatTool = None
  CbLauncherDir = "/media/DATA/SteamLibrary/steamapps/common/Elite Dangerous/"
  PreferredLanguage = None
  ApiUri = https://api.zaonce.net/
  Restart = None
  AutoUpdate = true
  MaxConcurrentDownloads = 4
  ForceUpdate = set []
  Processes = []
  FilterOverrides = seq [[FORC-FDEV-DO-1000, edo]]
  AdditionalProducts = [] }
2022-09-25 15:44:06.757 +02:00 [DBG] Unset LC_ALL. Using $LANG to determine correct UI culture
2022-09-25 15:44:06.788 +02:00 [INF] Elite Runtime
    Platform: Steam
    CobraBay Version: 0.4.6725.0
    Products Dir: /media/DATA/SteamLibrary/steamapps/common/Elite Dangerous/Products
2022-09-25 15:44:07.290 +02:00 [DBG] Got steam client
2022-09-25 15:44:07.290 +02:00 [DBG] Got steam pipe
2022-09-25 15:44:07.294 +02:00 [DBG] Got steam global user
2022-09-25 15:44:07.294 +02:00 [DBG] Got steam user
2022-09-25 15:44:07.295 +02:00 [DBG] Requesting steam auth ticket
2022-09-25 15:44:07.295 +02:00 [DBG] Got steam auth ticket
2022-09-25 15:44:07.298 +02:00 [DBG] Authenticating via Steam
2022-09-25 15:44:07.852 +02:00 [DBG] Successfully authenticated
2022-09-25 15:44:07.853 +02:00 [DBG] Disposing Steam resources
2022-09-25 15:44:07.853 +02:00 [DBG] Cancelling auth ticket
2022-09-25 15:44:07.853 +02:00 [DBG] closing steam
2022-09-25 15:44:07.856 +02:00 [INF] Logged in via Steam as: Ishiro Katsumi
2022-09-25 15:44:07.856 +02:00 [DBG] Getting authorized products
2022-09-25 15:44:09.498 +02:00 [DBG] Purchases Response:
{"purchases":[{"colour":"#f07b05","filter":"ed","directory":"elite-dangerous-64","serverargs":"","gameargs":"SeasonOne","sortkey":"06","product_name":"Elite Dangerous","product_sku":"FORC-FDEV-D-1010","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#f07b05","filter":"eda","directory":"elite-dangerous-64","serverargs":"","gameargs":"CQCArena","sortkey":"20","product_name":"Elite Dangerous: Arena","product_sku":"FORC-FDEV-D-1012","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-arena/en.html"},{"colour":"#f07b05","filter":"ed","directory":"COMBAT_TUTORIAL_DEMO","serverargs":"","gameargs":"","sortkey":"30","product_name":"Single Player Combat Training","product_sku":"COMBAT_TUTORIAL_DEMO","template":"http://hosting.zaonce.net/launcher-steam/elite/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-64","serverargs":"","gameargs":"","sortkey":"05","product_name":"Elite Dangerous: Horizons","product_sku":"FORC-FDEV-D-1013","template":"http://hosting.zaonce.net/launcher-steam/elite-dangerous-horizons/en.html"},{"colour":"#0a8bd6","filter":"edh","directory":"elite-dangerous-odyssey-64","serverargs":"","gameargs":"","sortkey":"00","product_name":"Elite Dangerous: Odyssey","product_sku":"FORC-FDEV-DO-1000","template":"http://hosting.zaonce.net/launcher-steam/odyssey/en.html"}]}
2022-09-25 15:44:09.521 +02:00 [DBG] Authorized Products: Elite Dangerous: Odyssey,Elite Dangerous: Horizons,Elite Dangerous,Elite Dangerous: Arena,Single Player Combat Training
2022-09-25 15:44:09.522 +02:00 [INF] Checking for updates
2022-09-25 15:44:09.530 +02:00 [DBG] Disabling 'Single Player Combat Training'. Unable to find product at '/media/DATA/SteamLibrary/steamapps/common/Elite Dangerous/Products/COMBAT_TUTORIAL_DEMO/VersionInfo.txt'
2022-09-25 15:44:11.292 +02:00 [INF] Available Products:
	Elite Dangerous: Odyssey  FORC-FDEV-DO-1000 Up to Date
	Elite Dangerous: Horizons FORC-FDEV-D-1013  Up to Date
	Elite Dangerous           FORC-FDEV-D-1010  Up to Date
	Elite Dangerous: Arena    FORC-FDEV-D-1012  Up to Date
2022-09-25 15:44:11.388 +02:00 [INF] Launching Elite Dangerous: Odyssey
2022-09-25 15:44:11.524 +02:00 [DBG] Process: /media/DATA/SteamLibrary/steamapps/common/Elite Dangerous/Products/elite-dangerous-odyssey-64/EliteDangerous64.exe "ServerToken 362...aea534...79a3c5...99ca977c257 cf0...972f5b...dc1afe...26b9a2...e7847e...eb16ba...0b45e9...3069d8...1465ce...1a4972...755e2c...1f7a1e...cd9153...d94456...d45e48...aeaab2...16657d...088e5f...cb083b...1e7164...f7163a...d5526b...39193a...b62ca5...3ddf0e...0ff7c3...5ab7e3...a8ab85...392218...a2acc0...ea8b5b...de63a7...336d39...a7b7af...402564...5d7c65...98d023...d89cab...04c89d...c6c4e4...9d67d4...d568aec65 " /language English\\UK /steam /novr
2022-09-25 15:44:30.021 +02:00 [INF] Shutdown Elite Dangerous: Odyssey
```

**Comment by rfvgyhn** [comment]
It looks like proton launches differently. `steam-launch-wrapper` isn't a process I've seen in the past. I'll need to do some experimenting.

**Comment by rfvgyhn** [comment]
I was able to replicate this issue on my end and I think it's fixed. Please reopen it if the [CI build](https://github.com/rfvgyhn/min-ed-launcher/actions/runs/3123169955) doesn't work for you.

**Comment by zezic** [comment]
I confirm that it's fixed now. Thank you!

**Comment by HerrCraziDev** [comment]
Fixed for me as well, thanks <3

**Comment by nirui** [comment]
Fixed for me too! Thanks.
